name: build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: "8.0.x"
    - name: Build
      run: dotnet build OpenMeteo
    - name: Test
      run: dotnet test OpenMeteo.Tests 